/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Approx.xs. Do not edit this file, edit Approx.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Approx.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "patchlevel.h"
#ifdef __cplusplus
}
#endif

#include "apse.h"

#if PATCHLEVEL < 5
# define PL_na na
#endif

#line 28 "Approx.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 71 "Approx.c"

XS(XS_String__Approx_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       croak_xs_usage(cv,  "CLASS, pattern, ...");
    {
	char*	CLASS = (char *)SvPV_nolen(ST(0));
	SV*	pattern = ST(1);
	apse_t *	RETVAL;
#line 27 "Approx.xs"
        apse_t*         ap;
        apse_size_t     edit_distance;
        IV pattern_size = sv_len(pattern);
        if (items == 2)
                edit_distance = ((pattern_size-1)/10)+1;
        else if (items == 3)
                edit_distance = (apse_size_t)SvIV(ST(2));
        else {
                warn("Usage: new(pattern[, edit_distance])\n");
                XSRETURN_UNDEF;
        }
        ap = apse_create((unsigned char *)SvPV(pattern, PL_na),
                         pattern_size, edit_distance);
        if (ap) {
                RETVAL = ap;
        } else {
                warn("unable to allocate");
                XSRETURN_UNDEF;
        }
#line 107 "Approx.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_String__Approx_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "ap");
    {
	apse_t*	ap;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::DESTROY() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 53 "Approx.xs"
        apse_destroy(ap);
#line 137 "Approx.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_String__Approx_match); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_match)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text");
    {
	apse_t*	ap;
	SV*	text = ST(1);
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::match() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 60 "Approx.xs"
        RETVAL = apse_match(ap,
                            (unsigned char *)SvPV(text, PL_na),
                            sv_len(text));
#line 169 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_match_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_match_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text");
    {
	apse_t*	ap;
	SV*	text = ST(1);
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::match_next() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 71 "Approx.xs"
        RETVAL = apse_match_next(ap,
                                 (unsigned char *)SvPV(text, PL_na),
                                 sv_len(text));
#line 202 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_index); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_index)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text");
    {
	apse_t*	ap;
	SV*	text = ST(1);
	apse_ssize_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::index() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 82 "Approx.xs"
        RETVAL = apse_index(ap,
                            (unsigned char *)SvPV(text, PL_na),
                            sv_len(text));
#line 235 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_slice); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_slice)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	apse_t*	ap;
	SV*	text = ST(1);
#line 93 "Approx.xs"
        apse_size_t     match_begin;
        apse_size_t     match_size;
#line 260 "Approx.c"

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::slice() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 96 "Approx.xs"
	if (ap->use_minimal_distance) {
	  apse_slice(ap,
		     (unsigned char *)SvPV(text, PL_na),
		     (apse_size_t)sv_len(text),
		     &match_begin,
		     &match_size);
	  EXTEND(sp, 3);
	  PUSHs(sv_2mortal(newSViv(match_begin)));
	  PUSHs(sv_2mortal(newSViv(match_size)));
	  PUSHs(sv_2mortal(newSViv(ap->edit_distance)));
	} else if (apse_slice(ap,
			      (unsigned char *)SvPV(text, PL_na),
			      (apse_size_t)sv_len(text),
			      &match_begin,
			      &match_size)) {
	  EXTEND(sp, 2);
	  PUSHs(sv_2mortal(newSViv(match_begin)));
	  PUSHs(sv_2mortal(newSViv(match_size)));
        }
#line 288 "Approx.c"
	PUTBACK;
	return;
    }
}


XS(XS_String__Approx_slice_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_slice_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	apse_t*	ap;
	SV*	text = ST(1);
#line 121 "Approx.xs"
        apse_size_t     match_begin;
        apse_size_t     match_size;
#line 313 "Approx.c"

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::slice_next() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 124 "Approx.xs"
        if (apse_slice_next(ap,
                            (unsigned char *)SvPV(text, PL_na),
                            sv_len(text),
                            &match_begin,
                            &match_size)) {
                EXTEND(sp, 2);
                PUSHs(sv_2mortal(newSViv(match_begin)));
                PUSHs(sv_2mortal(newSViv(match_size)));
		if (ap->use_minimal_distance) {
		    EXTEND(sp, 1);
		    PUSHs(sv_2mortal(newSViv(ap->edit_distance)));
		}
        }
#line 335 "Approx.c"
	PUTBACK;
	return;
    }
}


XS(XS_String__Approx_set_greedy); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_greedy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "ap");
    {
	apse_t*	ap;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_greedy() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 142 "Approx.xs"
        apse_set_greedy(ap, 1);
#line 363 "Approx.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_String__Approx_set_caseignore_slice); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_caseignore_slice)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "ap, ...");
    {
	apse_t*	ap;
#line 148 "Approx.xs"
        apse_size_t     offset;
        apse_size_t     size;
        apse_bool_t     ignore;
#line 385 "Approx.c"
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_caseignore_slice() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 152 "Approx.xs"
        offset = items < 2 ? 0 : (apse_size_t)SvIV(ST(1));
        size   = items < 3 ? ap->pattern_size : (apse_size_t)SvIV(ST(2));
        ignore = items < 4 ? 1 : (apse_bool_t)SvIV(ST(3));
        RETVAL = apse_set_caseignore_slice(ap, offset, size, ignore);
#line 400 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_insertions); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_insertions)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, insertions");
    {
	apse_t*	ap;
	apse_size_t	insertions = SvUV(ST(1));
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_insertions() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 164 "Approx.xs"
        RETVAL = apse_set_insertions(ap, insertions);
#line 431 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_deletions); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_deletions)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, deletions");
    {
	apse_t*	ap;
	apse_size_t	deletions = SvUV(ST(1));
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_deletions() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 173 "Approx.xs"
        RETVAL = apse_set_deletions(ap, deletions);
#line 462 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_substitutions); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_substitutions)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, substitutions");
    {
	apse_t*	ap;
	apse_size_t	substitutions = SvUV(ST(1));
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_substitutions() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 182 "Approx.xs"
        RETVAL = apse_set_substitutions(ap, substitutions);
#line 493 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_edit_distance); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_edit_distance)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, edit_distance");
    {
	apse_t*	ap;
	apse_size_t	edit_distance = SvUV(ST(1));
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_edit_distance() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 191 "Approx.xs"
        RETVAL = apse_set_edit_distance(ap, edit_distance);
#line 524 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_get_edit_distance); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_get_edit_distance)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "ap");
    {
	apse_t*	ap;
	apse_size_t	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::get_edit_distance() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 199 "Approx.xs"
        ST(0) = sv_newmortal();
        sv_setiv(ST(0), apse_get_edit_distance(ap));
#line 554 "Approx.c"
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_text_initial_position); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_text_initial_position)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text_initial_position");
    {
	apse_t*	ap;
	apse_size_t	text_initial_position = SvUV(ST(1));
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_text_initial_position() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 207 "Approx.xs"
        RETVAL = apse_set_text_initial_position(ap, text_initial_position);
#line 584 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_text_final_position); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_text_final_position)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text_final_position");
    {
	apse_t*	ap;
	apse_size_t	text_final_position = SvUV(ST(1));
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_text_final_position() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 216 "Approx.xs"
        RETVAL = apse_set_text_final_position(ap, text_final_position);
#line 615 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_text_position_range); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_text_position_range)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, text_position_range");
    {
	apse_t*	ap;
	apse_size_t	text_position_range = SvUV(ST(1));
	apse_bool_t	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_text_position_range() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 225 "Approx.xs"
        RETVAL = apse_set_text_position_range(ap, text_position_range);
#line 646 "Approx.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_String__Approx_set_minimal_distance); /* prototype to pass -Wmissing-prototypes */
XS(XS_String__Approx_set_minimal_distance)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "ap, b");
    {
	apse_t*	ap;
	apse_bool_t	b = (apse_bool_t)SvIV(ST(1));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		ap = (apse_t *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "String::Approx::set_minimal_distance() -- ap is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 234 "Approx.xs"
        apse_set_minimal_distance(ap, b);
#line 675 "Approx.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_String__Approx); /* prototype to pass -Wmissing-prototypes */
XS(boot_String__Approx)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("String::Approx::new", XS_String__Approx_new, file);
        newXS("String::Approx::DESTROY", XS_String__Approx_DESTROY, file);
        newXS("String::Approx::match", XS_String__Approx_match, file);
        newXS("String::Approx::match_next", XS_String__Approx_match_next, file);
        newXS("String::Approx::index", XS_String__Approx_index, file);
        newXS("String::Approx::slice", XS_String__Approx_slice, file);
        newXS("String::Approx::slice_next", XS_String__Approx_slice_next, file);
        newXS("String::Approx::set_greedy", XS_String__Approx_set_greedy, file);
        newXS("String::Approx::set_caseignore_slice", XS_String__Approx_set_caseignore_slice, file);
        newXS("String::Approx::set_insertions", XS_String__Approx_set_insertions, file);
        newXS("String::Approx::set_deletions", XS_String__Approx_set_deletions, file);
        newXS("String::Approx::set_substitutions", XS_String__Approx_set_substitutions, file);
        newXS("String::Approx::set_edit_distance", XS_String__Approx_set_edit_distance, file);
        newXS("String::Approx::get_edit_distance", XS_String__Approx_get_edit_distance, file);
        newXS("String::Approx::set_text_initial_position", XS_String__Approx_set_text_initial_position, file);
        newXS("String::Approx::set_text_final_position", XS_String__Approx_set_text_final_position, file);
        newXS("String::Approx::set_text_position_range", XS_String__Approx_set_text_position_range, file);
        newXS("String::Approx::set_minimal_distance", XS_String__Approx_set_minimal_distance, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

